---
name: "Code Quality: tflint"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  lint:
    name: tflint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup `terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6

      - name: Initialize `terraform`
        run: terraform init

      - name: Setup `tflint`
        uses: terraform-linters/setup-tflint@v1
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ".tflint.hcl"

      - name: Initialize `tflint`
        run: tflint --init

      - name: Run `tflint`
        run: tflint --format compact
